version: "3"
services:
  postgres:
    image: postgres:15
    container_name: "postgresDZ"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - MyPG_Network
networks:
  MyPG_Network:
    driver: bridge